version: 0.1

# currently not implemented -> need change firebase.json in /autorun
rootDir: ./ # A root directory for the watcher (all dirs inside are also watched)
serviceAcc: ./serviceAcc.json

auth:
  - getFromProd: 5 # initialize Firestore with the first x users from the Firebase Authentication with the project specified by serviceAcc
  - getFromProd: ['user1', 'user2'] #

  - users:
     - id: user3
       data: '{"email":"user3@gmail.com"}'

firestore:
  - collection: workspaces
    getFromProd: 5 # initialize Firestore the first x users in collection "workspaces", from Firebase Firestore with the project specified by serviceAcc

  - collection: workspaces
    getFromProd: ['ws1', 'ws2']

  - collection: workspaces
    docs:
      - id: ws3
        data: '{"color":"mountain"}'

functions:
  - name: requestFromJSON
    type: https
    payload: '{"color":"island"}'

  - name: requestFromProduction
    type: https
    payload:
      doc:
        collection: workspaces
        id: ws1

  - name: onCreateTriggerFromJSON
    type: firestore
    trigger: onCreate
    doc:
      collection: workspaces
      id: ws5
      data: '{"color":"forest"}'

  - name: onCreateTriggerFromProduction
    type: firestore
    trigger: onCreate
    doc:
      collection: workspaces
      id: ws5

  - name: onDeleteTrigger
    type: firestore
    trigger: onDelete
    doc:
      collection: users
      id: user-id

  - name: onUpdateTrigger
    type: firestore
    trigger: onUpdate
    doc:
      collection: users
      id: ws6
      data: '{"color":"swamp"}'

  - name: onCreateAuthFromJSON
    type: auth
    trigger: onCreate
    user:
      id: ws7
      data: '{"color":"plains"}'
s
  - name: onCreateAuthFromProduction
    type: auth
    trigger: onCreate
    user:
      id: user5

  - name: onDeleteAuth
    type: auth
    trigger: onDelete
    user:
      id: user1