version: 0.1
rootDir: "./" # A root directory for the watcher (all dirs inside are also watched)
serviceAcc: "./serviceAcc.json"
firestore:
  - collection: users
    docs:
      - '{"id":"user1", "home":"hell"}'
      - '{"id":"user2", "home":"heaven"}'
  - collection: users
    get: 5
functions:
  - name: helloWorld
    trigger: http
    data:
      collection: users
      take: id1
  - name: helloWorld
    trigger: http
    data: '{"id":"user1"}'
  - name: createWorkspace
    trigger: onCreate
    data:
      collection: users
      create: '{"id":"user3", "home":"hearthstone"}'
  - name: updateSlug
    trigger: onUpdate
    data:
      collection: workspace
      update:
        doc: doc-id
        new: '{"slug": "my-new-slug"}'
  - name: deleteAcc
    trigger: onDelete
    data:
      collection: users
      doc: user-id
